name: qs
description: A query string encoding and encoding library. It's better to use with protobuf(go), gorilla/schema(go) and qs(js).
version: 0.0.1-nullsafety.3

homepage: https://github.com/Ronbb/qs
publish_to: https://pub.dev

environment:
  # This must remain a tight constraint until nnbd is stable
  sdk: '>=2.10.0-0 <2.11.0'

dependencies:

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.1
  test: ^1.16.0-nullsafety.5 
